spring.application.name=WarehouseSlot
spring.datasource.url=jdbc:mysql://localhost:3306/WarehouseSlot
spring.datasource.username=root
spring.datasource.password=chari@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080